string class_name
float32 confidence
float32 x_min
float32 y_min
float32 x_max
float32 y_max
float32 x_center 
float32 y_center  

# ------------------------------------------------------------------------------
# This message definition was created by Xavier Vicent.
# If you use or reference this message, please give appropriate credit.
# ------------------------------------------------------------------------------

